

# This website is about my academic and professional experience!

Here's back to the [homepage](index.html).

Lin Yang
408-666-5488  
ly2565@cumc.columbia.edu  
New York, NY 10032

EDUCATION
 
COLUMBIA UNIVERSITY MAILMAN SCHOOL OF PUBLIC HEALTH                                   New York, NY                                                  Master of Science, Biostatistics                                                                                                  09/2021-present
Track in Public Health Data Science 
Relevant Courses: Data Science Using R, Probability, Biostatistical Methods, Principles of Epidemiology
UNIVERSITY OF CALIFORNIA, BERKELEY                                                                                     Berkeley, CA                                                                       
Bachelor of Arts, Molecular and Cell Biology                                                                      08/2017-05/2019
GPA: 3.8
Honors and Rewards: Graduated with Distinction in General Scholarship
                                              The UC Berkeley Undergraduate Scholarship

WORK EXPERIENCE

CHENGDU CHAOYOUAI TECHNOLOGY CO., LTD.                                           	              Chengdu, China
English Editor                                                                                                                                04/2021-07/2021
•	Accurately entered teaching data of over 20 courses, including text, audio, pictures, and video into company production platform to present teaching material on app. Received commendations from team leader.
•	Composed detailed teaching notes, including vocabulary, grammar explanations, example sentences, and exercises for over 20 English courses.
•	Managed a group of 8 intern editors, including assigning task, monitoring daily productivity, answering questions, and implementing modifications to improve overall effectiveness.
•	Cooperated with group members in developing standard operations procedures (SOP) to effectively train new interns.

VOLUNTEER EXPERIENCE

REGENERATIVE SCIENCES INSTITUTE                                                                                        Sunnyvale, CA
Lab Assistant                                                                                                                                 05/2019-12/2019 
•	Independently cared for and maintained laboratory planaria strains two days a week to ensure that their growth status was good for experiments.
•	Checked experiment material and reagent supplies and reported it to supervisor weekly.

BREATHE CALIFORNIA OF THE BAY AREA                                                                                   San Jose, CA
Presentation Interpreter                                                                                                                             05/2018
•	Performed interpretation duty from English to Chinese Mandarin in a live speaking presentation with an audience of over 100 senior residents, translated and answered inquiries pertaining to the presentation.
•	Translated the speaker’s lecture slides to an accessible language, understood the audience of the presentation to achieve the desired effect.
•	Performed administrative tasks like: scene arrangement, guest registration, and flyer distribution. 

Skills
	
•	Data entry	•	Leadership
•	Team Collaboration	•	Time management




